[2022-08-21 15:56:51,339] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:56:51,354] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:56:51,354] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:56:51,354] {taskinstance.py:1377} INFO - Starting attempt 12 of 12
[2022-08-21 15:56:51,354] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:56:51,375] {taskinstance.py:1397} INFO - Executing <Task(FTPToS3Operator): ftp_to_s3_task> on 2022-08-21 14:00:00+00:00
[2022-08-21 15:56:51,380] {standard_task_runner.py:52} INFO - Started process 2890 to run task
[2022-08-21 15:56:51,384] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-08-21T14:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmp3v91cy2p', '--error-file', '/tmp/tmpttio9opm']
[2022-08-21 15:56:51,384] {standard_task_runner.py:80} INFO - Job 14: Subtask ftp_to_s3_task
[2022-08-21 15:56:51,466] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [running]> on host 97b471418068
[2022-08-21 15:56:51,568] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=12
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T14:00:00+00:00
[2022-08-21 15:56:51,586] {base.py:68} INFO - Using connection ID 'ftp_default' for task execution.
[2022-08-21 15:56:51,958] {ftp.py:184} INFO - Retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:57:03,294] {ftp.py:186} INFO - Finished retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:57:03,311] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2022-08-21 15:57:03,312] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-08-21 15:57:03,421] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 150, in execute
    self.__upload_to_s3_from_ftp(self.ftp_path, self.s3_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 109, in __upload_to_s3_from_ftp
    acl_policy=self.acl_policy,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 611, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 349, in _main
    Bucket=bucket, Key=key, **extra_args
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 879, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 940, in _convert_to_request_dict
    api_params, operation_model
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Key, value: 0, valid min length: 1
[2022-08-21 15:57:03,436] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20220821T140000, start_date=20220821T155651, end_date=20220821T155703
[2022-08-21 15:57:03,453] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task ftp_to_s3_task (Parameter validation failed:
Invalid length for parameter Key, value: 0, valid min length: 1; 2890)
[2022-08-21 15:57:03,469] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-21 15:57:03,502] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
