[2022-08-21 15:21:38,523] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:21:38,536] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:21:38,536] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:21:38,536] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2022-08-21 15:21:38,536] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:21:38,554] {taskinstance.py:1397} INFO - Executing <Task(FTPToS3Operator): ftp_to_s3_task> on 2022-08-21 14:00:00+00:00
[2022-08-21 15:21:38,560] {standard_task_runner.py:52} INFO - Started process 1250 to run task
[2022-08-21 15:21:38,563] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-08-21T14:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmp49wyt9km', '--error-file', '/tmp/tmpr8w_7krs']
[2022-08-21 15:21:38,563] {standard_task_runner.py:80} INFO - Job 8: Subtask ftp_to_s3_task
[2022-08-21 15:21:38,644] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [running]> on host 97b471418068
[2022-08-21 15:21:38,738] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T14:00:00+00:00
[2022-08-21 15:21:38,752] {base.py:68} INFO - Using connection ID 'ftp_default' for task execution.
[2022-08-21 15:21:39,352] {ftp.py:184} INFO - Retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:21:49,197] {ftp.py:186} INFO - Finished retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:21:49,214] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2022-08-21 15:21:49,215] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-08-21 15:21:49,329] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 150, in execute
    self.__upload_to_s3_from_ftp(self.ftp_path, self.s3_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 109, in __upload_to_s3_from_ftp
    acl_policy=self.acl_policy,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 611, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 349, in _main
    Bucket=bucket, Key=key, **extra_args
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 879, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 937, in _convert_to_request_dict
    api_params, operation_model, context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 973, in _emit_api_params
    context=context,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/handlers.py", line 276, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "caged/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2022-08-21 15:21:49,344] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20220821T140000, start_date=20220821T152138, end_date=20220821T152149
[2022-08-21 15:21:49,372] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task ftp_to_s3_task (Parameter validation failed:
Invalid bucket name "caged/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 1250)
[2022-08-21 15:21:49,391] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-21 15:21:49,450] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
