[2022-08-21 15:31:49,911] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:31:49,924] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-08-21 15:31:49,924] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:31:49,924] {taskinstance.py:1377} INFO - Starting attempt 9 of 9
[2022-08-21 15:31:49,924] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 15:31:49,945] {taskinstance.py:1397} INFO - Executing <Task(FTPToS3Operator): ftp_to_s3_task> on 2022-08-21 14:00:00+00:00
[2022-08-21 15:31:49,951] {standard_task_runner.py:52} INFO - Started process 1737 to run task
[2022-08-21 15:31:49,955] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-08-21T14:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmpsaygxd1m', '--error-file', '/tmp/tmpdxvs5svd']
[2022-08-21 15:31:49,956] {standard_task_runner.py:80} INFO - Job 11: Subtask ftp_to_s3_task
[2022-08-21 15:31:50,039] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [running]> on host 97b471418068
[2022-08-21 15:31:50,140] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T14:00:00+00:00
[2022-08-21 15:31:50,154] {base.py:68} INFO - Using connection ID 'ftp_default' for task execution.
[2022-08-21 15:31:50,789] {ftp.py:184} INFO - Retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:31:56,501] {ftp.py:186} INFO - Finished retrieving file from FTP: /pdet/microdados/CAGED/2007/CAGEDEST_122007.7z
[2022-08-21 15:31:56,517] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2022-08-21 15:31:56,518] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-08-21 15:31:57,417] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 349, in _main
    Bucket=bucket, Key=key, **extra_args
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 150, in execute
    self.__upload_to_s3_from_ftp(self.ftp_path, self.s3_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 109, in __upload_to_s3_from_ftp
    acl_policy=self.acl_policy,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 611, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 296, in upload_file
    filename, '/'.join([bucket, key]), e
boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmps9t0ldy8 to minio/caged/: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
[2022-08-21 15:31:57,430] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20220821T140000, start_date=20220821T153149, end_date=20220821T153157
[2022-08-21 15:31:57,460] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task ftp_to_s3_task (Failed to upload /tmp/tmps9t0ldy8 to minio/caged/: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.; 1737)
[2022-08-21 15:31:57,495] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-21 15:31:57,550] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
