[2022-10-15 21:42:40,556] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-10-15 21:42:40,575] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [queued]>
[2022-10-15 21:42:40,576] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:42:40,576] {taskinstance.py:1377} INFO - Starting attempt 24 of 24
[2022-10-15 21:42:40,576] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:42:40,605] {taskinstance.py:1397} INFO - Executing <Task(SFTPToS3Operator): ftp_to_s3_task> on 2022-08-21 14:00:00+00:00
[2022-10-15 21:42:40,615] {standard_task_runner.py:52} INFO - Started process 11879 to run task
[2022-10-15 21:42:40,620] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-08-21T14:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmpimi33k7h', '--error-file', '/tmp/tmphbkprti0']
[2022-10-15 21:42:40,620] {standard_task_runner.py:80} INFO - Job 63: Subtask ftp_to_s3_task
[2022-10-15 21:42:40,737] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-08-21T14:00:00+00:00 [running]> on host e1202d78ead4
[2022-10-15 21:42:40,890] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=24
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T14:00:00+00:00
[2022-10-15 21:42:40,941] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/sftp_to_s3.py", line 82, in execute
    ssh_hook = SSHHook(ssh_conn_id=self.sftp_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/hooks/ssh.py", line 147, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `ssh_default` isn't defined
[2022-10-15 21:42:40,950] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20220821T140000, start_date=20221015T214240, end_date=20221015T214240
[2022-10-15 21:42:40,973] {standard_task_runner.py:97} ERROR - Failed to execute job 63 for task ftp_to_s3_task (The conn_id `ssh_default` isn't defined; 11879)
[2022-10-15 21:42:40,992] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-15 21:42:41,065] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
