[2022-10-15 22:58:20,551] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: test_dag.upload_to_s3 scheduled__2022-10-14T00:00:00+00:00 [queued]>
[2022-10-15 22:58:20,561] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: test_dag.upload_to_s3 scheduled__2022-10-14T00:00:00+00:00 [queued]>
[2022-10-15 22:58:20,562] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 22:58:20,562] {taskinstance.py:1377} INFO - Starting attempt 7 of 7
[2022-10-15 22:58:20,562] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 22:58:20,578] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2022-10-14 00:00:00+00:00
[2022-10-15 22:58:20,584] {standard_task_runner.py:52} INFO - Started process 15375 to run task
[2022-10-15 22:58:20,587] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'upload_to_s3', 'scheduled__2022-10-14T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpk8z_8jxs', '--error-file', '/tmp/tmprjofmn1y']
[2022-10-15 22:58:20,588] {standard_task_runner.py:80} INFO - Job 85: Subtask upload_to_s3
[2022-10-15 22:58:20,660] {task_command.py:371} INFO - Running <TaskInstance: test_dag.upload_to_s3 scheduled__2022-10-14T00:00:00+00:00 [running]> on host e1202d78ead4
[2022-10-15 22:58:20,748] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-14T00:00:00+00:00
[2022-10-15 22:58:20,761] {base.py:68} INFO - Using connection ID 's3_conn' for task execution.
[2022-10-15 22:58:20,762] {base_aws.py:206} INFO - Credentials retrieved from login
[2022-10-15 22:58:20,814] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 9, in upload_to_s3
    hook.load_file(filename=filename, key=key, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 595, in load_file
    if not replace and self.check_for_key(key, bucket_name):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 438, in check_for_key
    obj = self.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 420, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 879, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 940, in _convert_to_request_dict
    api_params, operation_model
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Key, value: 0, valid min length: 1
[2022-10-15 22:58:20,825] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=test_dag, task_id=upload_to_s3, execution_date=20221014T000000, start_date=20221015T225820, end_date=20221015T225820
[2022-10-15 22:58:20,838] {standard_task_runner.py:97} ERROR - Failed to execute job 85 for task upload_to_s3 (Parameter validation failed:
Invalid length for parameter Key, value: 0, valid min length: 1; 15375)
[2022-10-15 22:58:20,879] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-15 22:58:20,950] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
