[2022-10-16 00:08:25,355] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T22:00:00+00:00 [queued]>
[2022-10-16 00:08:25,368] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T22:00:00+00:00 [queued]>
[2022-10-16 00:08:25,369] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 00:08:25,369] {taskinstance.py:1377} INFO - Starting attempt 8 of 8
[2022-10-16 00:08:25,369] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 00:08:25,389] {taskinstance.py:1397} INFO - Executing <Task(FTPToS3Operator): ftp_to_s3_task> on 2022-10-15 22:00:00+00:00
[2022-10-16 00:08:25,396] {standard_task_runner.py:52} INFO - Started process 18611 to run task
[2022-10-16 00:08:25,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-10-15T22:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmpvj4_r06s', '--error-file', '/tmp/tmpzr_kk10d']
[2022-10-16 00:08:25,400] {standard_task_runner.py:80} INFO - Job 106: Subtask ftp_to_s3_task
[2022-10-16 00:08:25,488] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T22:00:00+00:00 [running]> on host e1202d78ead4
[2022-10-16 00:08:25,608] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-15T22:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-15T22:00:00+00:00
[2022-10-16 00:08:25,623] {base.py:68} INFO - Using connection ID 'ftp_default' for task execution.
[2022-10-16 00:08:26,241] {ftp.py:184} INFO - Retrieving file from FTP: /pdet/microdados/NOVO CAGED/2020/202002/
[2022-10-16 00:08:26,721] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 150, in execute
    self.__upload_to_s3_from_ftp(self.ftp_path, self.s3_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/ftp_to_s3.py", line 99, in __upload_to_s3_from_ftp
    remote_full_path=remote_filename, local_full_path_or_buffer=local_tmp_file.name
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ftp/hooks/ftp.py", line 185, in retrieve_file
    conn.retrbinary(f'RETR {remote_file_name}', callback)
  File "/usr/local/lib/python3.7/ftplib.py", line 449, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.7/ftplib.py", line 406, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.7/ftplib.py", line 372, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/local/lib/python3.7/ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.7/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 501 'RETR': Invalid number of parameters.
[2022-10-16 00:08:26,735] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20221015T220000, start_date=20221016T000825, end_date=20221016T000826
[2022-10-16 00:08:26,753] {standard_task_runner.py:97} ERROR - Failed to execute job 106 for task ftp_to_s3_task (501 'RETR': Invalid number of parameters.; 18611)
[2022-10-16 00:08:26,776] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-16 00:08:26,827] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
